[graph]
targets = [
    "x86_64-unknown-linux-musl",
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-musl",
    "aarch64-unknown-linux-gnu",
    "aarch64-apple-darwin",
    "x86_64-pc-windows-msvc",
]
all-features = true

[advisories]
yanked = "deny"
ignore = []

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "ISC",
    "BSD-3-Clause",
    "Unicode-3.0",
    "Zlib",
]
exceptions = [
]

[bans]
multiple-versions = "deny"
deny = [
    "openssl",
    "curl",
    "chrono",
]
skip = [
]
skip-tree = [
    "windows-sys",
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = []
