output = "win_bindings.rs"
binds = [
    "CloseHandle",
    "CreateEventA",
    "ERROR_INVALID_FUNCTION",
    "ERROR_IO_PENDING",
    "ERROR_LOCK_VIOLATION",
    "FILE_FLAG_OVERLAPPED",
    "INFINITE",
    "LockFileEx",
    "LOCKFILE_EXCLUSIVE_LOCK",
    "LOCKFILE_FAIL_IMMEDIATELY",
    "UnlockFile",
    "WaitForSingleObject",
    "WAIT_IO_COMPLETION",
    "WAIT_OBJECT_0",
    "WAIT_TIMEOUT",
]

[bind-mode]
mode = "minwin"

[bind-mode.config]
enum-style = "minwin"
fix-naming = true
use-rust-casing = true
